const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const PROFILE_REQUEST = 'PROFILE_REQUEST';
const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
const PROFILE_FAILURE = 'PROFILE_FAILURE';

const KNOWLEDGE_BASE_REQUEST = 'KNOWLEDGE_BASE_REQUEST';
const KNOWLEDGE_BASE_SUCCESS = 'KNOWLEDGE_BASE_SUCCESS';
const KNOWLEDGE_BASE_FAILURE = 'KNOWLEDGE_BASE_FAILURE';

const OUTAGES_REQUEST = 'OUTAGES_REQUEST';
const OUTAGES_SUCCESS = 'OUTAGES_SUCCESS';
const OUTAGES_FAILURE = 'OUTAGES_FAILURE';

const TICKETING_FAILURE = 'TICKETING_FAILURE';
const TICKETING_SUCCESS = 'TICKETING_SUCCESS';
const TICKETING_REQUEST = 'TICKETING_REQUEST';


const THEME_FAILURE = 'THEME_FAILURE';
const THEME_SUCCESS = 'THEME_SUCCESS';
const THEME_REQUEST = 'THEME_REQUEST';

const CREATE_TICKETING_FAILURE = 'CREATE_TICKETING_FAILURE';
const CREATE_TICKETING_SUCCESS = 'CREATE_TICKETING_SUCCESS';
const CREATE_TICKETING_REQUEST = 'CREATE_TICKETING_REQUEST';

const CREATE_CALLBACK_FAILURE = 'CREATE_CALLBACK_FAILURE';
const CREATE_CALLBACK_SUCCESS = 'CREATE_CALLBACK_SUCCESS';
const CREATE_CALLBACK_REQUEST = 'CREATE_CALLBACK_REQUEST';

const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

const TENANT_INFO_REQUEST = 'TENANT_INFO_REQUEST';
const TENANT_INFO_SUCCESS = 'TENANT_INFO_SUCCESS';
const TENANT_INFO_FAILURE = 'TENANT_INFO_FAILURE';

const AGENT_INFO_REQUEST = 'AGENT_INFO_REQUEST';
const AGENT_INFO_SUCCESS = 'AGENT_INFO_SUCCESS';
const AGENT_INFO_FAILURE = 'AGENT_INFO_FAILURE';

const CONFIG_SUCCESS = 'CONFIG_SUCCESS';

const HOME_ENTER = 'HOME_ENTER';
const HOME_EXIT = 'HOME_EXIT';

const LOADING = 'LOADING';

const DEMO_ENTER = 'DEMO_ENTER';
const DEMO_EXIT = 'DEMO_EXIT';

const SURVEY_ENTER = 'SURVEY_ENTER';
const SURVEY_EXIT = 'SURVEY_EXIT';

const VIDEO_ENTER = 'VIDEO_ENTER';
const VIDEO_EXIT = 'VIDEO_EXIT';

const SCHEDULE_ENTER = 'SCHEDULE_ENTER';
const SCHEDULE_EXIT = 'SCHEDULE_EXIT';

const Login_Details = 'Login_Details';

const Sidebar_Details = 'Sidebar_Details';

const STYLE_REQUEST = 'STYLE_REQUEST';
const STYLE_SUCCESS = 'STYLE_SUCCESS';
const BASICCONFIG_SUCCESS = 'BASICCONFIG_SUCCESS'
const STYLE_FAILURE = 'STYLE_FAILURE';


const IVA_REQUEST = 'IVA_REQUEST';
const IVA_SUCCESS = 'IVA_SUCCESS';
const IVA_FAILURE = 'IVA_FAILURE';


const CONTACT_REQUEST = 'CONTACT_REQUEST';
const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
const CONTACT_FAILURE = 'CONTACT_FAILURE';


module.exports = {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,

  PROFILE_REQUEST,
  PROFILE_SUCCESS,
  PROFILE_FAILURE,

  KNOWLEDGE_BASE_REQUEST,
  KNOWLEDGE_BASE_SUCCESS,
  KNOWLEDGE_BASE_FAILURE,

  OUTAGES_REQUEST,
  OUTAGES_SUCCESS,
  OUTAGES_FAILURE,

  TICKETING_FAILURE,
  TICKETING_SUCCESS,
  TICKETING_REQUEST,

  THEME_FAILURE,
  THEME_SUCCESS,
  THEME_REQUEST,

  CREATE_TICKETING_FAILURE,
  CREATE_TICKETING_SUCCESS,
  CREATE_TICKETING_REQUEST,

  CREATE_CALLBACK_FAILURE,
  CREATE_CALLBACK_SUCCESS,
  CREATE_CALLBACK_REQUEST,

  AUTHENTICATION_REQUEST,
  AUTHENTICATION_SUCCESS,
  AUTHENTICATION_FAILURE,

  TENANT_INFO_REQUEST,
  TENANT_INFO_SUCCESS,
  TENANT_INFO_FAILURE,

  AGENT_INFO_REQUEST,
  AGENT_INFO_SUCCESS,
  AGENT_INFO_FAILURE,

  CONFIG_SUCCESS,

  HOME_ENTER,
  HOME_EXIT,

  LOADING,

  DEMO_ENTER,
  DEMO_EXIT,

  VIDEO_ENTER,
  VIDEO_EXIT,

  SURVEY_ENTER,
  SURVEY_EXIT,

  SCHEDULE_ENTER,
  SCHEDULE_EXIT,

  Login_Details,
  Sidebar_Details,

  STYLE_REQUEST,
  STYLE_SUCCESS,
  BASICCONFIG_SUCCESS,
  STYLE_FAILURE,

  IVA_REQUEST,
  IVA_SUCCESS,
  IVA_FAILURE,


  CONTACT_REQUEST,
  CONTACT_SUCCESS,
  CONTACT_FAILURE,


};
